server:
  port: 8080
spring:
  data:
    mongodb:
      username: root
      password: example
      database: reviews
      port: 27017
      host: mongodb
      authentication-database: admin
  security:
    basic-auth:
      - username: user
        password: password
        roles:
          - ROLE_USER
      - username: admin
        password: admin
        roles:
          - ROLE_USER
          - ROLE_ADMIN
logging:
  level:
    root: INFO
    com.adidas.products.reviews: INFO
    org.springframework: INFO